service: serverless-customerapi-dynamodb

stage: ${opt:stage,'dev'}

custom:
    dynamodb: 
        start: 
            port: 8000
            inMemory: true
            migrate: true
            migration: 
                dir: offline/migrations

provider:
    name: aws
    runtime: nodejs10.x
    timeout: 30
    region: ${opt:region, 'ap-south-1'}
    custom:
    defaultStage: dev
    profiles:
      dev: devProfile
    iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:*"
        - "lambda:*"
        - "dynamodb:*"
        - "cognito-idp:*"
        - "ses:*"
      Resource: "*"


functions:
  getcustomerbyid:
    handler: handlers/getcustomerbyid.getcustomer
    events:
      - http:
          path: /handlers/{id}
          method: get
          cors: true
        
  createcustomer:
    handler: handlers/addcustomer.createcustomer
    events:
      - http:
          path: /handlers
          method: post
          cors: true
